import os
from datetime import datetime
from io import BytesIO
import pandas as pd
import plotly.express as px
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.cidfonts import UnicodeCIDFont

def generate_trend_report(
    df, 
    keywords, 
    start_date, 
    end_date, 
    time_unit, 
    model_metrics
):
    """트렌드 분석 PDF 리포트 생성"""
    
    # 폰트 등록
    pdfmetrics.registerFont(UnicodeCIDFont('HYSMyeongJo-Medium'))
    
    # 임시 이미지 경로 설정
    os.makedirs("temp", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    image_path = os.path.join("temp", f"trend_chart_{timestamp}.png")

    try:
        # 트렌드 차트 생성
        df_vis_report = df.copy()
        df_long_report = df_vis_report.melt(id_vars="date", var_name="keyword", value_name="ratio")
        fig_report = px.line(
            df_long_report, x="date", y="ratio", color="keyword", markers=True, 
            title="키워드별 트렌드 변화 (Trend Comparison)",
            color_discrete_sequence=px.colors.qualitative.Set2
        )
        fig_report.update_layout(
            paper_bgcolor="white", plot_bgcolor="white", font=dict(color="black"),
            margin=dict(l=40, r=30, t=60, b=40), legend=dict(orientation="h", y=-0.2)
        )
        fig_report.write_image(image_path, scale=2, engine="kaleido")

        # PDF 생성
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        # 제목
        c.setFont("HYSMyeongJo-Medium", 18)
        c.setFillColor(colors.HexColor("#0D47A1"))
        c.drawCentredString(width / 2, height - 2 * cm, "TrendLens 통합 분석 리포트")

        # 생성 일시
        c.setFont("HYSMyeongJo-Medium", 11)
        c.setFillColor(colors.black)
        c.drawString(2 * cm, height - 3 * cm, f"생성일시: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        start_y = height - 4.5 * cm

        # 1. 분석 개요
        _draw_analysis_overview(c, start_y, keywords, start_date, end_date, time_unit)
        start_y -= 3.2 * cm

        # 2. 데이터 요약
        start_y = _draw_data_summary(c, start_y, df)
        start_y -= 2.2 * cm

        # 3. 트렌드 시각화
        start_y = _draw_trend_visualization(c, start_y, image_path, width, height)
        start_y -= 1.5 * cm

        # 4. 모델 성능 요약
        if model_metrics:
            start_y = _draw_model_performance(c, start_y, model_metrics, height)

        # 푸터
        c.setFont("HYSMyeongJo-Medium", 9)
        c.setFillColor(colors.gray)
        c.drawString(2 * cm, 1.5 * cm, "Generated by TrendLens | Naver Trend Analysis Dashboard")

        c.save()
        buffer.seek(0)
        return buffer

    except Exception as e:
        raise Exception(f"PDF 생성 중 오류 발생: {e}")

    finally:
        if os.path.exists(image_path):
            os.remove(image_path)

def _draw_analysis_overview(c, start_y, keywords, start_date, end_date, time_unit):
    """분석 개요 섹션 그리기"""
    c.setFont("HYSMyeongJo-Medium", 14)
    c.drawString(2 * cm, start_y, "1. 분석 개요")
    start_y -= 0.7 * cm
    
    c.setFont("HYSMyeongJo-Medium", 10)
    c.drawString(2.5 * cm, start_y, f"- 분석 키워드: {', '.join(keywords)}")
    start_y -= 0.5 * cm
    c.drawString(2.5 * cm, start_y, f"- 조회 기간: {start_date} ~ {end_date} ({time_unit} 단위)")
    start_y -= 0.5 * cm

    
    return start_y

def _draw_data_summary(c, start_y, df):
    """데이터 요약 섹션 그리기"""
    c.setFont("HYSMyeongJo-Medium", 14)
    c.drawString(2 * cm, start_y, "2. 데이터 및 트렌드 주요 요약")
    start_y -= 0.7 * cm

    # 현재 시점 최고 키워드
    last_ratios = df.tail(1).drop(columns='date', errors='ignore').iloc[0]
    top_kw = last_ratios.idxmax()
    
    c.setFont("HYSMyeongJo-Medium", 10)
    c.drawString(2.5 * cm, start_y, f"- 현재 시점({df['date'].max().strftime('%Y-%m-%d')}) 검색량 최고 키워드: {top_kw}")
    
    return start_y

def _draw_trend_visualization(c, start_y, image_path, width, height):
    """트렌드 시각화 섹션 그리기"""
    c.setFont("HYSMyeongJo-Medium", 14)
    c.drawString(2 * cm, start_y, "3. 트렌드 비교 시각화")
    start_y -= 0.7 * cm

    if os.path.exists(image_path):
        image_width = width - 4 * cm
        image_height = image_width * 0.5

        if start_y - image_height < 4 * cm:
            c.showPage()
            start_y = height - 3 * cm
            
        c.drawImage(image_path, 2 * cm, start_y - image_height, width=image_width, height=image_height)
        start_y -= image_height
    
    return start_y

def _draw_model_performance(c, start_y, model_metrics, height):
    """모델 성능 섹션 그리기 (전체 모델 → 최적 모델 순서로 출력)"""
    c.setFont("HYSMyeongJo-Medium", 14)
    c.drawString(2 * cm, start_y, "4. 예측 모델 성능 요약")
    start_y -= 0.7 * cm

    data = pd.DataFrame(model_metrics)

    if data.empty:
        c.setFont("HYSMyeongJo-Medium", 10)
        c.drawString(2.5 * cm, start_y, "- 모델 성능 데이터가 없습니다.")
        return start_y

    # -------------------------------
    # (1) 전체 모델 성능 목록 출력
    # -------------------------------
    c.setFont("HYSMyeongJo-Medium", 11)
    c.drawString(2.5 * cm, start_y, "전체 모델별 성능 요약:")
    start_y -= 0.6 * cm

    c.setFont("HYSMyeongJo-Medium", 10)
    for _, row in data.iterrows():
        if start_y < 2 * cm:  # 페이지 여백 보호
            c.showPage()
            start_y = height - 3 * cm
            c.setFont("HYSMyeongJo-Medium", 10)

        c.drawString(
            3.0 * cm,
            start_y,
            f"- [{row['키워드']}] {row['모델명']} → RMSE: {row['RMSE']:.3f}, MAPE: {row['MAPE(%)']:.2f}%"
        )
        start_y -= 0.45 * cm

    start_y -= 0.4 * cm

    # -------------------------------
    # (2) 최적 모델(=RMSE 최소)만 요약
    # -------------------------------
    best_models = data.loc[data.groupby('키워드')['RMSE'].idxmin()].reset_index(drop=True)
    c.setFont("HYSMyeongJo-Medium", 11)
    c.drawString(2.5 * cm, start_y, "키워드별 최적 예측 모델 (RMSE 최소 기준):")
    start_y -= 0.6 * cm

    c.setFont("HYSMyeongJo-Medium", 10)
    for _, row in best_models.iterrows():
        if start_y < 2 * cm:
            c.showPage()
            start_y = height - 3 * cm
            c.setFont("HYSMyeongJo-Medium", 10)

        c.drawString(
            3.0 * cm,
            start_y,
            f"- [{row['키워드']}] 최적 모델: {row['모델명']} (RMSE {row['RMSE']:.3f}, MAPE {row['MAPE(%)']:.2f}%)"
        )
        start_y -= 0.45 * cm

    return start_y
